version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.0

    working_directory: ~/repo

    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.7/site-packages
      - restore_cache:
      # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}

      - run:
          name: install dependencies
          command: |
            pipenv install -d

      - save_cache:
          key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - ".venv"
            - "/usr/local/bin"
            - "/usr/local/lib/python3.6/site-packages"

      - run:
          name: run tests
          command: |
            cd src/logogram/
            pipenv run coverage run --rcfile=../../.coveragerc manage.py test
            pipenv run coverage report --rcfile=../../.coveragerc
            pipenv run coverage html --rcfile=../../.coveragerc
            export COVERALLS_REPO_TOKEN=${COVERALLS_REPO_TOKEN}
            pipenv run coveralls --rcfile=../../.coveragerc

      - store_artifacts:
          path: src/logogram/htmlcov
          destination: test-reports

  application-deployment:
    docker:
      - image: circleci/python:3.6-jessie-browsers
    steps:
      - checkout
      - run: bash .circleci/deploy.sh

workflows:
  version: 2
  deploy-application:
    jobs:
      - build
      - application-deployment:
          requires:
            - build
