# Generated by Django 2.1.5 on 2019-01-24 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logogram_v1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flashcards',
            name='jargon',
        ),
        migrations.RemoveField(
            model_name='flashcards',
            name='privacy',
        ),
        migrations.DeleteModel(
            name='Jargons',
        ),
    ]
