# Generated by Django 2.1.5 on 2019-01-24 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logogram_v1', '0002_auto_20190124_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='first_name'),
        ),
        migrations.AlterField(
            model_name='users',
            name='last_name',
            field=models.CharField(max_length=30, verbose_name='last_name'),
        ),
    ]
