# Generated by Django 2.1.5 on 2019-01-26 10:12

from django.db import migrations, models
import logogram_v1.domain_persistence.users.models


class Migration(migrations.Migration):

    dependencies = [
        ('logogram_v1', '0003_auto_20190124_1300'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='users',
            managers=[
                ('objects', logogram_v1.domain_persistence.users.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='users',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
        migrations.AlterField(
            model_name='flashcards',
            name='description',
            field=models.TextField(blank=True, verbose_name='flash_card_description'),
        ),
        migrations.AlterField(
            model_name='flashcards',
            name='name',
            field=models.CharField(max_length=30, verbose_name='flash_card_name'),
        ),
    ]
